@startuml hof

!$client = "Client"
!$kt = "LambdaRPC.kt"
!$jl = "LambdaRPC.jl"
!$lib = "Libservice"

box "Client process" #LightBlue
participant "$client"
participant "$kt"
end box

box "Libservice process"
participant "$jl"
participant "$lib"
end box

"$client" -> "$kt" : Invoke eval5 { it + m }
"$kt" -> "$jl" : Frontend-Backend call
"$jl" -> "$lib" : Call fun eval5
"$lib" -> "$lib" : f(5)

"$lib" -> "$jl" : Invoke lambda frontend
"$jl" -> "$kt" : Frontend-Backend call
"$kt" -> "$client" : Call lambda backend
"$client" -> "$client" : { it + m }

"$client" -> "$kt" : Lambda call result
"$kt" -> "$jl" : Backend-Frontend result
"$jl" -> "$lib" : Lambda frontend result
"$lib" -> "$lib" : result

"$lib" -> "$jl" : eval5 backend result
"$jl" -> "$kt" : Backend-Frontend result
"$kt" -> "$client" : eval5 frontend result

@enduml
